/* 
 * File:   grafcet.h
 * Author: Table2
 *
 * Created on 20 octobre 2023, 09:46
 */

#ifndef GRAFCET_H
#define	GRAFCET_H

#define STATE_ATTENTE 0
#define STATE_ATTENTE_EN_COURS 1
#define STATE_AVANCE 2
#define STATE_AVANCE_EN_COURS 3
#define STATE_TOURNE_GAUCHE 4
#define STATE_TOURNE_GAUCHE_EN_COURS 5
#define STATE_TOURNE_DROITE 6
#define STATE_TOURNE_DROITE_EN_COURS 7
#define STATE_TOURNE_SUR_PLACE_GAUCHE 8
#define STATE_TOURNE_SUR_PLACE_GAUCHE_EN_COURS 9
#define STATE_TOURNE_SUR_PLACE_DROITE 10
#define STATE_TOURNE_SUR_PLACE_DROITE_EN_COURS 11
#define STATE_ARRET 12
#define STATE_ARRET_EN_COURS 13
#define STATE_RECULE 14
#define STATE_RECULE_EN_COURS 15
#define STATE_TOURNE_VITE_DROITE 16
#define STATE_TOURNE_VITE_GAUCHE 17
#define STATE_TOURNE_VITE_GAUCHE_EN_COURS 18
#define STATE_TOURNE_VITE_DROITE_EN_COURS 19
#define STATE_MARCHE_ARRIERE 20
#define STATE_MARCHE_ARRIERE_EN_COURS 21

#define PAS_D_OBSTACLE 0
#define OBSTACLE_A_GAUCHE 1
#define OBSTACLE_A_DROITE 2
#define OBSTACLE_EN_FACE 3
#define OBSTACLE_EXTREME_GAUCHE 4
#define OBSTACLE_EXTREME_DROITE 5
#define OBSTACLE_DEVANT_DROITE 6
#define OBSTACLE_DEVANT_GAUCHE 7


void OperatingSystemLoop(void) ;
void SetNextRobotStateInAutomaticMode(void) ;

#endif	/* GRAFCET_H */

